version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "reserve-rec-public"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "reserve-rec-public"
region = "ca-central-1"
image_repositories = []
parameter_overrides=[
  "DistOriginPath=latest",
  "ApiGatewayId=changeme",
  "Env=dev",
  "AWSRegion=ca-central-1",
  "ApiStage=api"
]

[dev]
[dev.global]
[dev.global.parameters]
stack_name = "reserve-rec-public"

[dev.build.parameters]
cached = true
parallel = true

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[dev.sync.parameters]
watch = true

[dev.local_start_api.parameters]
warm_containers = "EAGER"

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "reserve-rec-public"
region = "ca-central-1"
image_repositories = []
parameter_overrides=[
  "DistOriginPath=latest",
  "ApiGatewayId=zloys5cfvf",
  "Env=dev",
  "AWSRegion=ca-central-1",
  "ApiStage=api"
]

[test]
[test.global]
[test.global.parameters]
stack_name = "reserve-rec-public"

[test.build.parameters]
cached = true
parallel = true

[test.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[test.sync.parameters]
watch = true

[test.local_start_api.parameters]
warm_containers = "EAGER"

[test.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "reserve-rec-public"
region = "ca-central-1"
image_repositories = []
parameter_overrides=[
  "DistOriginPath=latest",
  "ApiGatewayId=zloys5cfvf",
  "Env=test",
  "AWSRegion=ca-central-1",
  "ApiStage=api"
]

[prod]
[prod.global]
[prod.global.parameters]
stack_name = "reserve-rec-public"

[prod.build.parameters]
cached = true
parallel = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[prod.sync.parameters]
watch = true

[prod.local_start_api.parameters]
warm_containers = "EAGER"

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "reserve-rec-public"
region = "ca-central-1"
image_repositories = []
parameter_overrides=[
  "DistOriginPath=latest",
  "ApiGatewayId=zloys5cfvf",
  "Env=prod",
  "AWSRegion=ca-central-1",
  "ApiStage=api"
]